# Generated by Django 5.1.3 on 2025-01-14 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(max_length=100)),
            ],
            options={
                'permissions': [('can_create_lesson', 'Can create lesson'), ('can_view_lesson', 'Can view lesson'), ('can_update_lesson', 'Can update lesson'), ('can_delete_lesson', 'Can delete lesson')],
            },
        ),
        migrations.CreateModel(
            name='SchoolAdress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100)),
                ('building_number', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('courses', models.ManyToManyField(to='first_view.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('director', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='first_view.director')),
                ('address', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='first_view.schooladress')),
                ('teachers', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='first_view.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherLessonStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_view.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_view.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_view.teacher')),
            ],
            options={
                'unique_together': {('teacher', 'lesson', 'student')},
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField(choices=[('1', 1.0), ('1+', 1.5), ('2', 2.0), ('2+', 2.5), ('3', 3.0), ('3+', 3.5), ('4', 4.0), ('4+', 4.5), ('5', 5.0), ('5+', 5.5), ('6', 6.0)])),
                ('date', models.DateField(auto_now_add=True)),
                ('teacher_lesson_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_view.teacherlessonstudent')),
            ],
        ),
    ]
