# Generated by Django 5.1.3 on 2025-01-14 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_view', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={},
        ),
    ]
